Feature player section
chingu-voyages/v35-geckos-team-08 pull request #23
Opened 2021-12-23 00:45 UTC by bluwakpa

I tested this section on all mobile resolutions in Chrome, Safari, Firefox, and MS Edge. In Chrome iPhone 5/SE, I was able to get the css #76 .audioPlayer {} container to overlap the css #25 .episode_info_section {} once, but it now appears resolved after more testing. Please let me know if this is ready for merging to develop and I'll work on making this responsive for desktop. Thanks!

2021-12-23 06:55 UTC, shiv-chan requested changes
Thank you @bluwakpa for your work 👍
I checked the section on the browser and looks good to me!

One thing about the tablet, could you please make the width of the description block a bit narrow and make the player bigger for the tablets?
![スクリーンショット 2021-12-22 22 56 25](https://user-images.githubusercontent.com/51708229/147201604-a2a943a4-f59e-4cd5-b0f0-9655b8f2a6ef.png)

I left some comments which are almost the same as #20. ***you can reply to each comment if it's needed.**
Please check them out and update it 🙏

Thanks.

2021-12-23 06:55 UTC, shiv-chan commented on components/AudioPlayer.js
> +import { BsArrowRightShort } from 'react-icons/bs';
```suggestion
import { BsArrowLeftShort, BsArrowRightShort } from "react-icons/bs"
```
You can combine those and make them shorter like above.

2021-12-23 06:55 UTC, shiv-chan commented on components/AudioPlayer.js
> +import { FaPause } from 'react-icons/fa';
```suggestion
import { FaPlay, FaPause } from "react-icons/fa"
```
You can combine those and make them shorter like above.

2021-12-23 06:55 UTC, shiv-chan commented on components/AudioPlayer.js
> +		// progressBar.current.style.setProperty('--seek-before-width', `${progressBar.current.value / duration * 100}%`)
```suggestion
```
You can remove this.

2021-12-23 06:55 UTC, shiv-chan commented on components/AudioPlayer.js
> +export { AudioPlayer };
```suggestion
export default AudioPlayer
```
I assume that we export only `AudioPlayer`, so we can say `export default` like this.
@bluwakpa did you have any specific reason for it?

2021-12-23 06:55 UTC, shiv-chan commented on pages/index.js
> +import { AudioPlayer } from "../components/AudioPlayer"
```suggestion
import AudioPlayer from "../components/AudioPlayer"
```
If we say `export default` we can import `AudioPlayer` without curly brackets.

2021-12-23 06:55 UTC, shiv-chan commented on components/AudioPlayer.module.css
> +	/* @@ updated */
```suggestion
```
It was just a mark to see where I updated easily, you can remove all `/* @@ updated */` comments.

2021-12-23 06:55 UTC, shiv-chan commented on components/AudioPlayer.module.css
> +.forwardBackward {
```suggestion
.controlThirty {
```
**Suggestion**: it was used for the forward button as well. Naming `forwardBackward` might confuse so I suggest that name more general name like this.

2021-12-23 06:55 UTC, shiv-chan commented on components/AudioPlayer.module.css
> +}
```suggestion
position: relative;
}

.forwardBackward svg {
		position: relative;
		top: 0.2rem;
	}
```
![スクリーンショット 2021-12-13 0 05 55](https://user-images.githubusercontent.com/51708229/145774711-c2adac90-073d-4e46-bdd8-8f811b5f2edb.png)

Even though having `align-items: center`, the arrow and "30" align a bit off, so we can adjust it like this.
I haven't checked every device so it might be off again in the different devices.

2021-12-23 06:55 UTC, shiv-chan commented on components/AudioPlayer.module.css
> +	--seek-before-width: 0;
```suggestion
```
You can remove this.

2021-12-23 06:55 UTC, shiv-chan commented on components/AudioPlayer.module.css
> +}
```suggestion
```
You can remove this.

2021-12-23 06:55 UTC, shiv-chan commented on styles/globals.css
> +}
```suggestion
```
If we don't use `h5` anymore, we can remove all `h5` styles in here.

2021-12-27 09:03 UTC, Shiho317 reviewed
Hi, Makha!
I ran the code on my local and I checked function as well.
Then I found the fast forward button (30s) is not forward 30 second correctly on my browser.
Backward button is working well. Thanks.
And just in my suggestion, I thought it's better to make the total duration number of the bar is going to be decreasing depends on playing time.
But thank you for doing most difficult part!

2021-12-28 00:51 UTC, bluwakpa commented on components/AudioPlayer.module.css
> +}
Great suggestion! This seems to work.

2021-12-29 04:19 UTC, shiv-chan requested changes
Thanks for updating, @bluwakpa.
When you make any updates again, please re-assign reviewers.

Also, please remove `/* @@updated */` comments as I asked.
https://github.com/chingu-voyages/v35-geckos-team-08/pull/23#discussion_r774329254

About the media query, Shiho and I have the same way to set the media query.
The same break point or putting the commet like "/*================ Tablet ==================*/" or "/*================ Laptop ==================*/".

Please refer to our css modules such as `hero.module.css` or `about.module.css`.  You can find these in `develop` branch.

In order to have the same values, we left the note for each breakpoint in `globals.css` like below.
```css
/* For media query
- min-width -
Mobile M: 375px
Mobile L: 425px
Tablet: 768px
Laptop: 1024px
Desktop and more: 1440px
*/
```

As we work as a team, it's better to have the same style of coding and that makes it easy for all of us to read the code later on.

2021-12-29 04:19 UTC, shiv-chan commented on components/AudioPlayer.js
> +		progressBar.current.style.setProperty('--seek-before-width', `${progressBar.current.value / duration * 100}%`)
@bluwakpa sorry it seems like you wanna add this line, but please remove this line since we don't have this design... 🙏 

I've left comments about this before. Please check these out. 
https://github.com/chingu-voyages/v35-geckos-team-08/pull/20#discussion_r767467655
https://github.com/chingu-voyages/v35-geckos-team-08/pull/23#discussion_r774325939

2022-01-02 01:51 UTC, shiv-chan approved these changes
@bluwakpa Thank you for updating again, Makha 🙏 
The code is cleaner!

2022-01-02 01:56 UTC, shiv-chan commented
@bluwakpa I merged #26 now, so you can merge this into `develop` branch. Thanks!

2022-01-02 12:13 UTC, Shiho317 approved these changes
Its working well for me too and very nice layout.
Thank you @bluwakpa for working this section hard.
well done!!

2022-01-02 22:28 UTC, merged